### ISSUE TITLE
Ads appear with uBlock Origin when YouTube EXPERIMENT_FLAGS Tamer is enabled

### ISSUE THREAD

**Issue by lockieluke** [cyfung1031/userscript-supports#35]
Ads like this appears when Tabview-Youtube and YouTube EXPERIMENT_FLAGS Tamer are installed
![image](https://github.com/cyfung1031/Tabview-Youtube/assets/25424409/72be599d-83fa-482d-8f9e-dfe3d5d03b87)

**Comment by cyfung1031** [comment]
@lockieluke  Would you like to try the following ?

Instead of using uBO

use following scripts:

https://github.com/cyfung1031/userscript-supports/raw/main/tmp-480192.user.js
https://greasyfork.org/en/scripts/470428-youtube-experiment-flags-tamer
https://greasyfork.org/en/scripts/492004-youtube-stable-streaming


This combination is still under testing. It should solve your issue.

**Comment by lockieluke** [comment]
I found out disabling YouTube EXPERIMENT_FLAGS Tamer fixes the problem
