### ISSUE TITLE
Question about cpu tamer scripts.

### ISSUE THREAD

**Issue by ChromiaCat** [cyfung1031/userscript-supports#41]
Why are there so many? Is there a difference on what they do/how well they work?
They all have the same description and it's hard for me to figure out by code alone if they do different stuff.

**Comment by cyfung1031** [comment]
The main script (CPU Tamer by AnimationFrame) was created after the review of knoa's script "YouTube CPU Tamer".

That was the first attempt to help improving the YouTube smoothness that my PC was slow.

I am now using Macbook only so I no longer feel any slowness but just keep updating it.

Besides, I am now understanding more the related JS coding that might make the browser slow, so I have created other scripts to handle YouTube's js coding issue.

https://greasyfork.org/en/scripts/469878-youtube-super-fast-chat
https://greasyfork.org/en/scripts/473972-youtube-js-engine-tamer
(and one more for the chatroom but now it is still under developing)

Basically these scripts are already fixed the issues as much as possible. CPU Tamer Script might not be required.

-------------


### youtube-cpu-tamer-by-animationframe.user.js 
* This is the main script. However, it might make the PC getting slower instead. The root cause could be that the PC don't have graphics acceleration.

### youtube-cpu-tamer-dm.user.js
* This is the second main CPU tamer. I received the possible feedbacks for people who feel bad in using `youtube-cpu-tamer-by-animationframe`. So this is 2nd main CPU tamer.
* You can try and compare both. Sorry, I do not have a slow environment to do so.

------------

#### youtube-cpu-tamer-io.user.js , youtube-cpu-tamer-vf1.user.js, youtube-cpu-tamer-vf2.user.js
* These are just for testing. Don't install them.

### youtube-live-chat-tamer.js
* No use. Just an old file


-----------------------

## Conclusion

* If you think your PC is slow in watching YouTube. You might try to install. If it improves your environment, keep it. If it cannot improve or make it worse, uninstall it.

**Comment by cyfung1031** [comment]
No further response. Close.
