### ISSUE TITLE
Disable volume stable is broken.

### ISSUE THREAD

**Issue by ChromiaCat** [cyfung1031/userscript-supports#47]

**Comment by cyfung1031** [comment]
Please explain more because I cannot see your YouTube UI.

For me, this is an option in video player menu for some videos like https://www.youtube.com/watch?v=TIWRbR69Cjc.

By using https://greasyfork.org/en/scripts/494252-youtube-disable-volume-stable, the option should be removed.

Please describe what do you mean "Disable volume stable is broken."

The option is not removed? Since recent?

**Comment by ChromiaCat** [comment]
Without using your script, the Stable Volume toggle is there but disabled, document.querySelector("video").volume reports 0.702263367991081 for the video https://www.youtube.com/watch?v=XaabCdyQ-mA

Using your script, the toggle is gone but document.querySelector("video").volume still reports an actual or "Normalized" volume of 0.702263367991081

But using https://gist.github.com/RobotoSkunk/212fab73afa6df48f9438b56e18ba073 it does bring the document.querySelector("video").volume to a 1 and combining your script removes the toggle too.

**Comment by cyfung1031** [comment]
They are totally two different things!

### Volume Normalization

YouTube's volume normalization is a standard feature since long time ago. 
There is an [old script - YouTube Volume Curve Designer](https://greasyfork.org/en/scripts/404756-youtube-volume-curve-designer) (year 2020) for the volume changing.

Since the normalization is a standard feature so disabling it is not recommended. You will experience a volume setting different from other audiences.

(So I don't have any script to disable this feature. Your provided link is not doing the correct way so the sound might "crackle". The userscript "YouTube Volume Curve Designer" is doing the correct way and I believe the sound would not "crackle")


### Volume Stable

This is a new feature since 2023 I guess. (A/B testing ended in 2024)

(Not available to old videos, as there was no AI to analyze the video)

YouTube uses AI to prevent the sudden volume change. This would affect watching music video a lot.

My script is to disable this feature.

This is a visible option in player's menu. As it is an enhancement feature, users are able to toggle it off without any script.



### Userscript "YouTube Volume Assistant"

I have created a [userscript](https://greasyfork.org/en/scripts/466775-youtube-volume-assistant) previously to show the normalized volume when user is changing the volume. You can install it to see the actual volume.


<img width="1014" alt="Screen Shot 2024-07-12 at 7 36 43" src="https://github.com/user-attachments/assets/0943c3e5-3923-478e-8bc5-1bb536d909af">
