### ISSUE TITLE
Restore YouTube Username from Handle to Custom: Not working in Desktop Firefox when logged in

### ISSUE THREAD

**Issue by R3G3N3R4T0R** [cyfung1031/userscript-supports#9]
I suppose it is the same cause as https://github.com/yakisova41/return-youtube-comment-username/issues/43, with its corresponding fix https://github.com/yakisova41/return-youtube-comment-username/commit/8da40a3746f3d78ae3e382e2ca13af598561d2f4.

The script would not work on desktop Firefox when logged in. It works properly when not logged in on Firefox or if using chromium based browsers either logged in or not. No request is made to fetch the username in the Network tab, but I do not see any extra error messages either.

#### Reproduction Steps
1. Create a new profile in Firefox, load in TamperMonkey/ViolentMonkey and your script from GreasyFork.
2. Open [www.youtube.com](http://www.youtube.com/) and pick a video, better pause once the video is loaded but not required.
3. Scroll down and YouTube comments should have usernames, new `browser?key=` requests would appear if Network tab is open.
4. Log in to YouTube, and return to the same video.
5. Scroll down and YouTube comments should have handles, new `browser?key=` requests would not appear if Network tab is open.

#### Versions Tested
- v0.5.7 to v0.5.10 (Firefox 114.0.2/TamperMonkey v4.18.1)
- V0.5.10 (Firefox 114.0.2/ViolentMonkey v2.14.0)
- v0.5.10 to v0.5.14 (Librewolf 110.0.1/ViolentMonkey v2.14.0)

**Comment by cyfung1031** [comment]
Thanks for reporting.

This issue is due to YouTube native coding issue for their custom elements implementation in Firefox.
Therefore, it is not directly related to the account login status. It is not related to UserScript manager you used.

This issue would not happen in Chrome because Chrome and YouTube both belong to Google.

Please update to the latest version (>=0.5.16). Please close the issue if it works for you.

**Comment by R3G3N3R4T0R** [comment]
I can confirm it works now and thanks for your explanation. I didn't expect you to fix it in 2 hours at midnight.

I have attempted to remove all youtube cookies and the Firefox 114.0.2 with v0.5.10 test is done with a fresh profile as a separate instance(when my main profile is also running) logging into my main account. The problem persisted, led me to the conclusion that logging in is the cause of the issue.

PS: I have found YouTube UX becoming worse and worse, but community improvement and the creator base have sort of locked me in. I guess that have also put them in a bind if they want to keep that advantage. Rewriting it will probably just lead to another reddit situation.

**Comment by cyfung1031** [comment]
From my understanding, the YouTube engine rendering is set to your account + browser application. Clear cookie or fresh profile won't help. The javascript files are the same. The difference is your web page retrieved from YouTube server.
But it usually would not create big issue to your watching experience, just sometimes your userscripts or extensions might not work due to those weird configurations.

**Comment by cyfung1031** [comment]
I just upgraded the following script to make it more powerful to reset the YouTube settings, including those related to account login issue (incorrect account authorisation settings).

https://greasyfork.org/en/scripts/457255-reset-youtube-settings

Recommend that you can use it to reset once.

You can check in console window that 

Before:
typing `document.querySelector('ytd-watch-flexy').firstElementChild === null` and press enter, show `true`
After (success):
typing `document.querySelector('ytd-watch-flexy').firstElementChild === null` and press enter, show `false`

**Comment by R3G3N3R4T0R** [comment]
Confirmed this fixes the issue on my account and both scripts in their affected versions operates correctly on both of my systems after resetting on one of them. Should I report it back to yakisova41?
It might also be a good idea to direct users to that script as part of troubleshooting procedure.
